### ISSUE TITLE
1.0.0-alpha checklist ✅

### ISSUE THREAD

**Issue by j** [j/graphql-party#1]
Here are some things to work on before an initial beta release.  Most features have been already coded in a project I made for fun, so it's a matter of cleaning them up and writing tests.  Boy, it's been fun!

- [x] Add `@ObjectType` decorator.
- [x] Add `@Field` decorator.
- [x] Add `@FieldResolver` decorator so resolver functions can live in other places besides @ObjectType()
- [x] Add `@InputType` decorator.
- [x] Add `@Query` decorator for creating Query object types.
  - [x] Implement
  - [x] Schema creation tests
  - [x] Test resolver functions
- [x] Add `@Mutation` decorator for creating Mutation object types.
  - [x] Implement
  - [x] Schema creation tests
  - [x] Test resolver functions
- [x] Add `@Context` parameter decorator for field resolvers.
  - [x] Implement
  - [x] Create examples
  - [x] Complete integration tests
- [x] Add `@Arg` parameter decorator for field resolvers.
  - [x] Implement
  - [x] Create examples
  - [x] Complete integration tests
- [x] ~~Add `@Obj` parameter decorator for field resolvers.~~ (will do only if requested, you can until access if you don't use param decorators)
- [x] ~~Add `@Info` parameter decorator for field resolvers.~~ (will do only if requested, you can until access if you don't use param decorators)
- [x] Add tests for examples
- [x] Publish!
